added nearly completed lab3
Yzoop/BSU-2Degree-Operating-Systems pull request #1
Opened 2020-03-12 11:23 UTC by Yzoop

2020-03-12 20:02 UTC, pashatyl requested changes
Some code style was checked, behavior will be reviewed after fixes

2020-03-12 20:02 UTC, pashatyl commented on Lab3/include/avarage_thr.h
> +void avarage(void* avaragearg);
```suggestion
void average(void* avaragearg);
```

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/avarage_thr.cpp
> +    _endthread();
Do not use _endthread
https://stackoverflow.com/questions/26960199/using-endthread

2020-03-12 20:02 UTC, pashatyl commented on Lab3/include/avarage_thr.h
> +void avarage(void* avaragearg);
add const qualifiers everywhere it's possible

2020-03-12 20:02 UTC, pashatyl commented on Lab3/include/avarage_thr.h
> +void avarage(void* avaragearg);
please, use snake_case

2020-03-12 20:02 UTC, pashatyl commented on Lab3/include/labArgument.h
> +
unnecessary empty line

2020-03-12 20:02 UTC, pashatyl commented on Lab3/include/minmax_thr.h
> +#pragma once
_thr in file name looks really strange, for such cases use folder named Threads instead

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/avarage_thr.cpp
> +    std::cout << "\t" << arg->avarage << "\n";
Unnecessary multiple calls

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/avarage_thr.cpp
> +void avarage(void* avaragearg)
Too much responsibilities for function

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/main.cpp
> +﻿//#define _CRT_SECURE_NO_WARNINGS
remove

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/main.cpp
> +#include "minmax_thr.h"
different naming conventions in file naming

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/main.cpp
> +using namespace std;
use std:: explicitly

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/main.cpp
> +    for (int i = 0; i < array_size; i++) {
using std::copy + std::backward_inserter will be prettier

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/main.cpp
> +    arr = new int[array_size];
use std::vector instead

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/main.cpp
> +void read_size_to(int& size)
It would looks better in separated module

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/main.cpp
> +void begin_minmax_thread(const minmaxarg_t* minmaxarg)
also, to separated module

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/main.cpp
> +void begin_avarge_thread(const avaragearg_t* avaragearg)
Code duplication

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/minmax_thr.cpp
> +        Sleep(7);
magic number
Introduce define for enabling this testing call

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/minmax_thr.cpp
> +    int max = -INT_MAX;
why not INT_MIN? are you sure INT_MAX == - INT_MIN?

2020-03-12 20:02 UTC, pashatyl commented on Lab3/include/labArgument.h
> +	int arr_size, min, max, minId, maxId;
use multiple lines

2020-03-12 20:02 UTC, pashatyl commented on Lab3/src/minmax_thr.cpp
> +minmaxarg_t* get_new_minmax_structure(int* arr, int arr_size, int min, int max, int minid, int maxid)
isn't it a constructor?)

2020-03-12 20:33 UTC, Yzoop commented on Lab3/src/minmax_thr.cpp
> +minmaxarg_t* get_new_minmax_structure(int* arr, int arr_size, int min, int max, int minid, int maxid)
First steps of OOP

2020-03-14 10:03 UTC, Yzoop commented on Lab3/include/avarage_thr.h
> +void avarage(void* avaragearg);
An argument avaragearg is supposed to be changed while avarage() func is working

2020-04-08 09:45 UTC, closed without merging